

name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: macos-14
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer
    - name: Run tests
      run: sudo swift test --parallel -Xswiftc -DDISABLE_END_TO_END_TESTS -v
