

name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.9'
    - name: Run all tests
      run: swift test -Xswiftc -DDISABLE_END_TO_END_TESTS -v
